// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderSystem.Data;

#nullable disable

namespace OrderSystem.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20260706075406_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("OrderSystem.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@example.com",
                            FirstName = "Bob",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 3,
                            Email = "carol@example.com",
                            FirstName = "Carol",
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 4,
                            Email = "david@example.com",
                            FirstName = "David",
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 5,
                            Email = "eve@example.com",
                            FirstName = "Eve",
                            LastName = "Wilson"
                        });
                });

            modelBuilder.Entity("OrderSystem.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 29.98m
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 1,
                            OrderDate = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 19.99m
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 2,
                            OrderDate = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 14.5m
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 3,
                            OrderDate = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 4.75m
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 4,
                            OrderDate = new DateTime(2023, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 57.99m
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 5,
                            OrderDate = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 12.0m
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 2,
                            OrderDate = new DateTime(2023, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 9.99m
                        },
                        new
                        {
                            Id = 8,
                            CustomerId = 3,
                            OrderDate = new DateTime(2023, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 24.0m
                        },
                        new
                        {
                            Id = 9,
                            CustomerId = 4,
                            OrderDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 74.99m
                        },
                        new
                        {
                            Id = 10,
                            CustomerId = 5,
                            OrderDate = new DateTime(2023, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 22.5m
                        });
                });

            modelBuilder.Entity("OrderSystem.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 2,
                            UnitPrice = 9.99m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 2,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 19.99m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 3,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 14.5m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 4,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 4.75m
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 5,
                            ProductId = 8,
                            Quantity = 1,
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 5,
                            ProductId = 6,
                            Quantity = 4,
                            UnitPrice = 6.0m
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 6,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 12.0m
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 7,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 9.99m
                        },
                        new
                        {
                            Id = 9,
                            OrderId = 8,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 24.0m
                        },
                        new
                        {
                            Id = 10,
                            OrderId = 9,
                            ProductId = 9,
                            Quantity = 1,
                            UnitPrice = 49.99m
                        },
                        new
                        {
                            Id = 11,
                            OrderId = 9,
                            ProductId = 10,
                            Quantity = 1,
                            UnitPrice = 24.999m
                        },
                        new
                        {
                            Id = 12,
                            OrderId = 10,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 14.5m
                        },
                        new
                        {
                            Id = 13,
                            OrderId = 10,
                            ProductId = 10,
                            Quantity = 1,
                            UnitPrice = 8.0m
                        });
                });

            modelBuilder.Entity("OrderSystem.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Basic widget",
                            Name = "Widget A",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Advanced widget",
                            Name = "Widget B",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Useful gadget",
                            Name = "Gadget C",
                            Price = 14.50m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Another gadget",
                            Name = "Gadget D",
                            Price = 24.00m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Handy thing",
                            Name = "Thingamajig",
                            Price = 4.75m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Small doodad",
                            Name = "Doodad",
                            Price = 7.30m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Mysterious whatsit",
                            Name = "Whatsit",
                            Price = 12.00m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Complex doohickey",
                            Name = "Doohickey",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Multi-part contraption",
                            Name = "Contraption",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Handheld gizmo",
                            Name = "Gizmo",
                            Price = 5.25m
                        });
                });

            modelBuilder.Entity("OrderSystem.Models.Order", b =>
                {
                    b.HasOne("OrderSystem.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OrderSystem.Models.OrderItem", b =>
                {
                    b.HasOne("OrderSystem.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderSystem.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrderSystem.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OrderSystem.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OrderSystem.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
